import type { Metadata } from "next";
import { LegalDocument } from "@/components/inner/legal-document";

export const metadata: Metadata = {
  title: { absolute: "Terms of Use — OUMATRA" },
  description: "Terms governing access to and use of the OUMATRA website.",
  alternates: { canonical: "/terms" },
};

const sections = ["About This Website","Use of the Website","Intellectual Property","OUMATRA, KLANS and MEMRY","Third-Party Links","Accuracy of Information","No Offer or Investment Solicitation","Communications With OUMATRA","Unsolicited Ideas and Submissions","Website Availability","Disclaimer of Warranties","Limitation of Liability","Privacy","Changes to These Terms","Governing Law and Jurisdiction","Severability","Contact"] as const;
const sectionId = (index: number) => `terms-${index + 1}`;

export default function TermsPage() {
  return <LegalDocument title="Terms of Use" updated="August 2026" idPrefix="terms" sections={sections} intro={["These Terms of Use govern your access to and use of the OUMATRA website.", "By accessing or using this website, you agree to these Terms. If you do not agree, please do not use the website."]}>
        <section id={sectionId(0)}><h2>1. About This Website</h2><p>The OUMATRA website provides general information about OUMATRA, its philosophy, activities, companies, and related initiatives.</p><p>The website is intended for informational and corporate communication purposes.</p><p>Nothing on this website should be interpreted as financial, investment, legal, professional, or other regulated advice.</p></section>
        <section id={sectionId(1)}><h2>2. Use of the Website</h2><p>You may use this website for lawful purposes only.</p><p>You must not:</p><ul><li>use the website in violation of applicable law;</li><li>attempt to gain unauthorized access to the website, systems, or infrastructure;</li><li>interfere with or disrupt the website or its operation;</li><li>introduce malicious code, malware, automated attacks, or harmful technologies;</li><li>scrape, reproduce, or systematically extract website content in a manner that violates applicable law or these Terms;</li><li>impersonate OUMATRA or misrepresent an affiliation with OUMATRA;</li><li>use the website in a way that could damage OUMATRA, its companies, users, systems, or reputation.</li></ul></section>
        <section id={sectionId(2)}><h2>3. Intellectual Property</h2><p>Unless otherwise stated, the content and materials available on the OUMATRA website are owned by, licensed to, or used with permission by OUMATRA.</p><p>This may include:</p><ul><li>the OUMATRA name;</li><li>logos and brand assets;</li><li>website design;</li><li>text;</li><li>graphics;</li><li>illustrations;</li><li>visual systems;</li><li>photographs;</li><li>documents; and</li><li>other original materials.</li></ul><p>These materials may be protected by copyright, trademark, design, and other intellectual-property laws.</p><p>You may view and use the website for personal or legitimate informational purposes.</p><p>You may not copy, reproduce, modify, distribute, republish, sell, license, or commercially exploit OUMATRA content without prior written permission unless such use is permitted by applicable law.</p></section>
        <section id={sectionId(3)}><h2>4. OUMATRA, KLANS and MEMRY</h2><p>References to KLANS, MEMRY, or other companies, products, initiatives, or brands on this website are provided for informational purposes.</p><p>Each company or service may operate under its own:</p><ul><li>website;</li><li>terms of service;</li><li>privacy policy;</li><li>policies; and</li><li>user agreements.</li></ul><p>Use of those products or services may therefore be governed by separate terms.</p><p>These OUMATRA Terms of Use apply only to the OUMATRA corporate website unless expressly stated otherwise.</p></section>
        <section id={sectionId(4)}><h2>5. Third-Party Links</h2><p>The website may contain links to websites or services operated by third parties or by companies associated with OUMATRA.</p><p>Such links are provided for convenience and informational purposes.</p><p>OUMATRA does not control third-party websites and is not responsible for their content, availability, security, privacy practices, or terms.</p><p>Accessing external websites is at your own discretion and subject to their respective terms and policies.</p></section>
        <section id={sectionId(5)}><h2>6. Accuracy of Information</h2><p>OUMATRA aims to keep information on the website accurate and current.</p><p>However, the website may include information that is incomplete, outdated, preliminary, or subject to change.</p><p>Information regarding products, companies, development status, launch timelines, availability, or future plans should not be considered a binding commitment unless expressly stated otherwise.</p><p>OUMATRA may update, correct, remove, or modify website content at any time without notice.</p></section>
        <section id={sectionId(6)}><h2>7. No Offer or Investment Solicitation</h2><p>Nothing on this website constitutes:</p><ul><li>an offer to sell securities;</li><li>a solicitation to purchase securities;</li><li>investment advice;</li><li>a fundraising offer; or</li><li>an invitation to enter into an investment relationship.</li></ul><p>Any investment, partnership, or commercial opportunity would be governed by separate written agreements and applicable law.</p></section>
        <section id={sectionId(7)}><h2>8. Communications With OUMATRA</h2><p>You may contact OUMATRA through the contact information provided on the website.</p><p>Sending an email or other communication does not automatically create:</p><ul><li>a contractual relationship;</li><li>partnership;</li><li>fiduciary relationship;</li><li>employment relationship; or</li><li>other legal relationship with OUMATRA.</li></ul><p>Do not send confidential or proprietary information unless appropriate confidentiality arrangements are already in place.</p></section>
        <section id={sectionId(8)}><h2>9. Unsolicited Ideas and Submissions</h2><p>OUMATRA may receive ideas, proposals, suggestions, or other unsolicited submissions.</p><p>Unless a separate written agreement states otherwise, sending unsolicited material does not create an obligation for OUMATRA to:</p><ul><li>review the submission;</li><li>maintain it confidentially;</li><li>compensate the sender;</li><li>develop the idea; or</li><li>enter into a business relationship.</li></ul><p>Please avoid submitting confidential or proprietary ideas through general contact channels.</p></section>
        <section id={sectionId(9)}><h2>10. Website Availability</h2><p>OUMATRA does not guarantee that the website will always be available, uninterrupted, secure, or error-free.</p><p>The website may occasionally be unavailable due to:</p><ul><li>maintenance;</li><li>technical issues;</li><li>infrastructure changes;</li><li>security events;</li><li>upgrades; or</li><li>circumstances beyond our reasonable control.</li></ul><p>OUMATRA may modify, suspend, or discontinue any part of the website without prior notice.</p></section>
        <section id={sectionId(10)}><h2>11. Disclaimer of Warranties</h2><p>The website and its content are provided on an “as is” and “as available” basis to the extent permitted by applicable law.</p><p>OUMATRA does not make warranties or representations regarding:</p><ul><li>continuous availability;</li><li>completeness;</li><li>accuracy;</li><li>suitability for a particular purpose;</li><li>absence of errors; or</li><li>freedom from harmful components.</li></ul><p>Nothing in these Terms excludes warranties or rights that cannot lawfully be excluded.</p></section>
        <section id={sectionId(11)}><h2>12. Limitation of Liability</h2><p>To the maximum extent permitted by applicable law, OUMATRA will not be liable for indirect, incidental, special, consequential, or similar losses arising from or connected with your use of, inability to use, or reliance on this website.</p><p>This may include loss arising from:</p><ul><li>reliance on website information;</li><li>external links;</li><li>interruptions;</li><li>technical errors; or</li><li>unauthorized access beyond OUMATRA’s reasonable control.</li></ul><p>Nothing in these Terms limits liability where such limitation is prohibited by applicable law.</p></section>
        <section id={sectionId(12)}><h2>13. Privacy</h2><p>Use of the website is also subject to the <a href="/privacy">OUMATRA Privacy Policy</a>.</p><p>The Privacy Policy explains how personal information may be collected, used, protected, and handled.</p></section>
        <section id={sectionId(13)}><h2>14. Changes to These Terms</h2><p>OUMATRA may revise these Terms from time to time.</p><p>Changes will be published on this page together with an updated “Last updated” date.</p><p>Your continued use of the website after updated Terms become effective constitutes acceptance of those Terms to the extent permitted by applicable law.</p></section>
        <section id={sectionId(14)}><h2>15. Governing Law and Jurisdiction</h2><p>These Terms are governed by the laws of India.</p><p>Subject to applicable law, disputes relating to these Terms or use of the OUMATRA website will be subject to the jurisdiction of the competent courts in Ambala, Haryana, India.</p></section>
        <section id={sectionId(15)}><h2>16. Severability</h2><p>If any provision of these Terms is found to be invalid, unlawful, or unenforceable, the remaining provisions will continue in effect to the extent permitted by law.</p></section>
        <section id={sectionId(16)}><h2>17. Contact</h2><p><a href="/contact">Contact OUMATRA</a></p></section>
  </LegalDocument>;
}
